---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  This AWS CloudFormation Template configures an environment with the necessary resources to support the Serverless Round of the Identity Round-Robin Workshop.

Parameters:

  ResourcePrefix:
    Type: String
    Default: identity-wksp-permissionsboundary
    AllowedValues: 
      - identity-wksp-permissionsboundary
    Description: Prefix of resources created for this workshop.  

#  InstanceType: 
#    Type: String
#    Default: t2.micro
#    AllowedValues: 
#      - t2.micro
#      - t2.medium
#    Description: Pick a instance type for the Cloud9 environment 

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Resource Configuration"
        Parameters:
          - ResourcePrefix
          - TeamName

Mappings:

  Application: 
    bucket: 
      "name": "sa-security-specialist-workshops-us-west-2"
    prefix:
      "key": "identity-workshop/permissionboundary/logging-bucket/"

Resources:
  
  # Website Bucket Resources
  WebsiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 
        Fn::Join:
          - '-'
          - ["shared-logging", !Ref "AWS::AccountId", !Ref "AWS::Region","data"]

  # Resources to copy website content
  WebsiteContent:
    DependsOn:
      - WebsiteBucket
    Type: "Custom::S3Objects"
    Properties:
      ServiceToken: !GetAtt WebsiteContentLambda.Arn
      SourceBucket: !FindInMap [Application, bucket, name]
      SourcePrefix: !FindInMap [Application, prefix, key]
      Bucket: !Ref WebsiteBucket

  WebsiteContentLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 
        Fn::Join:
          - '-'
          - [!Ref ResourcePrefix, 'lambda-content']
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        -
          PolicyName: S3Access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Sid: AllowLogging
                Effect: Allow
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
              -
                Sid: SourceBucketReadAccess
                Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:GetObject"
                Resource:
                  - Fn::Join:
                    - ''
                    - ['arn:aws:s3:::', !FindInMap [Application, bucket, name]]
                  - Fn::Join:
                    - ''
                    - ['arn:aws:s3:::', !FindInMap [Application, bucket, name], '/', !FindInMap [Application, prefix, key],'*']
              -
                Sid: DestBucketWriteAccess
                Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                  - "s3:PutObjectVersionAcl"
                  - "s3:DeleteObject"
                  - "s3:DeleteObjectVersion"
                  - "s3:CopyObject"
                Resource:
                  - !Sub "arn:aws:s3:::${WebsiteBucket}"
                  - !Sub "arn:aws:s3:::${WebsiteBucket}/*"

  WebsiteContentLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 
        Fn::Join:
          - '-'
          - [!Ref ResourcePrefix, 'content']
      Description: Copies objects from a source S3 bucket to a destination S3 bucket.
      Handler: index.handler
      Runtime: python2.7
      Role: !GetAtt WebsiteContentLambdaRole.Arn
      Timeout: 120
      Code:
        ZipFile: |
          from botocore.exceptions import ClientError
          import os
          import json
          import cfnresponse
          import boto3
          import logging

          # Create S3 clinet
          s3 = boto3.client('s3')

          # Set Logging
          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def handler(event, context):
            
            logger.info("Received event: %s" % json.dumps(event))
            
            # Set Variables
            source_bucket = event['ResourceProperties']['SourceBucket']
            source_prefix = event['ResourceProperties'].get('SourcePrefix') or ''
            bucket = event['ResourceProperties']['Bucket']
            prefix = event['ResourceProperties'].get('Prefix') or ''

            # Set Initial CFN Response
            result = cfnresponse.SUCCESS

            try:
              
              # Create or Update Event
              if event['RequestType'] == 'Create' or event['RequestType'] == 'Update':
                paginator = s3.get_paginator('list_objects_v2')
                page_iterator = paginator.paginate(Bucket=source_bucket, Prefix=source_prefix)
                
                for key in {x['Key'] for page in page_iterator for x in page['Contents']}:
                  dest_key = os.path.join(prefix, os.path.relpath(key, source_prefix))
                  if not key.endswith('/'):
                    print 'copy {} to {}'.format(key, dest_key)
                    s3.copy_object(CopySource={'Bucket': source_bucket, 'Key': key}, Bucket=bucket, Key = dest_key, ACL='public-read')

                result = cfnresponse.SUCCESS

              # Delete Event
              elif event['RequestType'] == 'Delete':
                paginator = s3.get_paginator('list_objects_v2')
                page_iterator = paginator.paginate(Bucket=bucket, Prefix=prefix)

                objects = [{'Key': x['Key']} for page in page_iterator for x in page['Contents']]
                s3.delete_objects(Bucket=bucket, Delete={'Objects': objects})

                result = cfnresponse.SUCCESS
            except ClientError as e:
              logger.error('Error: %s', e)
              
              result = cfnresponse.FAILED

            cfnresponse.send(event, context, result, {})
    
  # Cloud9 Environment
  pbcloudnineenv:
    Type : AWS::Cloud9::EnvironmentEC2
    Properties: 
        Description: "Cloud9 environment for the permissions boundary advanced workshop"
        AutomaticStopTimeMinutes: 120
        #InstanceType: !Ref InstanceType
        InstanceType: t2.micro
        Name: "workshop-environment"
        SubnetId: !Ref Subnet

  # We will use admin privileges for now
  #pbcloudninerole:
  #  Type : AWS::IAM::Role
  #  Properties:
  #      RoleName: 'pbcloudninerole'
  #      AssumeRolePolicyDocument: 
  #        Version: "2012-10-17"
  #        Statement: 
  #          - 
  #            Effect: "Allow"
  #            Principal: 
  #              Service: 
  #                - "ec2.amazonaws.com"
  #                - "cloud9.amazonaws.com"
  #            Action: 
  #              - "sts:AssumeRole"

  # VPC for Cloud9
  SystemVPC:
    Type: AWS::EC2::VPC
    Properties:
        CidrBlock: 192.168.0.0/16
        EnableDnsHostnames: true
        EnableDnsSupport: true
        Tags:
          - Key: Created-for
            Value: PB-Workshop
   
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
        Tags:
          - Key: Name
            Value: !Ref ResourcePrefix
              
  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
        InternetGatewayId:
          Ref: InternetGateway
        VpcId: !Ref SystemVPC
         
  RouteTable:
    DependsOn:
    - SystemVPC
    Type: AWS::EC2::RouteTable
    Properties:
        Tags:
          - Key: Name
            Value: !Ref ResourcePrefix
        VpcId: !Ref SystemVPC
         
  PublicRoute:
    DependsOn:
        - RouteTable
        - GatewayAttachment
    Type: AWS::EC2::Route
    Properties:
        DestinationCidrBlock: 0.0.0.0/0
        GatewayId: !Ref InternetGateway
        RouteTableId: !Ref RouteTable
        
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
        CidrBlock: 192.168.0.0/24
        MapPublicIpOnLaunch: true
        Tags:
          - Key: Name
            Value: !Ref ResourcePrefix
        VpcId: !Ref SystemVPC
        AvailabilityZone: 
          Fn::Select: 
              - 0
              - Fn::GetAZs: ""
        
  SubnetAssoc:
    DependsOn:
        - Subnet
        - RouteTable
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
        RouteTableId: !Ref RouteTable
        SubnetId: !Ref Subnet
  
  SubnetTwo:
    Type: AWS::EC2::Subnet
    Properties:
        CidrBlock: 192.168.128.0/24
        MapPublicIpOnLaunch: true
        Tags:
          - Key: Name
            Value: !Ref ResourcePrefix
        VpcId: !Ref SystemVPC
        AvailabilityZone: 
          Fn::Select: 
              - 1
              - Fn::GetAZs: ""
        
  SubnetTwoAssoc:
    DependsOn:
        - SubnetTwo
        - RouteTable
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
        RouteTableId: !Ref RouteTable
        SubnetId: !Ref SubnetTwo
        
  PublicNACL:
    Type: AWS::EC2::NetworkAcl
    Properties:
        VpcId: !Ref SystemVPC
        Tags:
          - Key: Network
            Value: Public
          
  InboundPublicNACLEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
        NetworkAclId: !Ref PublicNACL
        RuleNumber: 100
        Protocol: -1
        RuleAction: allow
        Egress: false
        CidrBlock: '0.0.0.0/0'
        PortRange:
          From: 0
          To: 65535
          
  OutboundPublicNACLEntry:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
        NetworkAclId: !Ref PublicNACL
        RuleNumber: 100
        Protocol: -1
        RuleAction: allow
        Egress: true
        CidrBlock: 0.0.0.0/0
        PortRange:
          From: 0
          To: 65535
          
  SubnetNACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
        SubnetId: !Ref Subnet
        NetworkAclId: !Ref PublicNACL
        
  SubnetTwoNACLAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
        SubnetId: !Ref SubnetTwo
        NetworkAclId: !Ref PublicNACL

  # Policy for a user trying out modules on a Cloud9 environment 
  # pbcloudninepolicy:
  #  Type : AWS::IAM::Policy
  #  Properties: 
  #      PolicyName : 'pb-cloudnine-policy'
  #      PolicyDocument : 
  #        Version: "2012-10-17"
  #        Statement:
  #          -
  #            Effect: "Allow"
  #            Action: "*"
  #            Resource: "*"
  #      Roles:
  #        - !Ref pbcloudninerole

#  Outputs: 